name: CICICPipeline
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
       -name: Checkout the repository
        uses: actions/checkout@v2
 
       -name: Run the script
        run: python hello.py

  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      -name: Checkout the repository
       uses: actions/checkout@v2

      -name: Create an artifact folder
       run: mkdir myartifact

       -name: create a artifact file
        run: echo "This is python artifact" > myartifact/artifact.txt