name: CICICPipeline
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run the script
        run: python hello.py

  Build:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create an artifact
        uses: actions/upload-artifact@v4
        with:
           name: myartifact
           path: myartifact/artifact.txt